---
include:

  - board: jiran_ble_lite_left

  - board: jiran_ble_lite_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: jiran_ble_lite_left_with_studio

  - board: jiran_ble_lite_right
